version: '3.9'
services:
  db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamerent
      POSTGRES_PASSWORD: gamerentpass
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - postgres-db:/var/lib/postgres
    command: -p 5433
volumes:
  postgres-db: