spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gamerent
    username: gamerent
    password: gamerentpass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db.changelog/changelog.yml
  security:
    jwt:
      secret: yhbr543hjncui986dvfscr43wnkio90654qwsaxd43rfvgdt09
      expired: 3600000
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@example.com
    password: 12345
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
game-rent:
  scheduling:
    account-blocking: 0 0 * * * *
  currency:
    data-path: https://www.cbr-xml-daily.ru/daily_json.js