spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${USER_DATABASE}
    password: ${USER_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db.changelog/changelog.yml
  security:
    jwt:
      secret: ${JWT_SECRET_PHRASE}
      expired: 3600000
