spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gamerent
    username: gamerent
    password: gamerentpass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db.changelog/changelog.yml
  security:
    jwt:
      secret: ssssssssssssssssssssssssssssssssssssss
      expired: 3600000
server:
    port: 8081
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_SENDER}
#    password: ${EMAIL_PASSWORD}
#    protocol: smtp
#    properties.mail.smtp:
#        auth: true
#        starttls.enable: true
#        ssl.trust: smtp.gmail.com
#game-rent:
#  scheduling:
#    account-blocking: 0 0 * * * *
